- hosts: all
  become: yes
  vars:
    greetings: Hello everyone!
    hp: httpd
    source: /home/pooja/index.html
    destination: /var/www/html/

  tasks:
  - name: Ansible Simple Variable Example Usage
    debug:
      msg: "{{ greetings }}, Let’s learn Ansible variables"

  - name: install
    dnf: 
      name: "{{ hp }}"
      state: latest

  - name: for background
    ansible.builtin.service:
      name: "{{ hp }}"
      state: started

  - name: copy file
    copy:
      src: "{{ source }}"
      dest: "{{ destination }}"


